backend:
  name: github
  repo: taimoorsattar7/taimoorsattar.dev
  branch: master
  # base_url: https://link.vercel.app
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: "content/blogs"
    slug: "index"
    author: "{{author}}"
    path: "{{title}}/index"
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Description", name: "description", widget: "string" }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { label: Tags, name: tags, widget: list }
      - {
          label: Featured Post,
          name: featuredpost,
          widget: boolean,
          default: false,
        }
      - {
          label: Featured Image,
          name: featuredimage,
          widget: image,
          required: false,
        }
  - name: page
    label: page
    folder: "src/pages"
    slug: "{{slug}}"
    author: "{{author}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Description", name: "description", widget: "string" }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { label: Tags, name: tags, widget: list }
      - {
          label: Featured Image,
          name: featuredimage,
          widget: image,
          required: false,
        }
  - name: "book"
    label: "Book"
    folder: "content/books"
    create: true
    slug: "index"
    author: "{{author}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - label: "Pricing Table"
        name: "Pricing"
        minimize_collapsed: true
        widget: "list"
        fields:
          - { label: NAME, name: name, widget: string, default: "name" }
          - { label: PRICE, name: price, widget: number, default: "Pricing" }
          - { label: "CURRENCY", name: buyLink, widget: text }
          - label: "INTERVAL"
            name: "interval"
            widget: "select"
            options: ["month", "6 month", "year"]
          - { label: BUTTON TEXT, name: btntxt, widget: string }
          - { label: BUTTON LINK, name: btnlink, widget: string }
          - { label: EXERPT, name: exerpt, widget: string }
      - { label: "EXERPT", name: "exerpt", widget: "string" }
      - { name: date, label: DATE, widget: date }
      - { name: body, label: BODY, widget: markdown }
      - { label: Tags, name: TAGS, widget: list }
      - { label: "BUY LINK", name: buyLink, widget: text }
      - {
          label: FEATURE IMAGE,
          name: featuredimage,
          widget: image,
          required: false,
        }
      - { label: "POPULAR", name: "popular", widget: "boolean", default: false }
